name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: ""
    validations:
      required: true
  - type: textarea
    id: what-browser
    attributes:
      label: What browser are you using?
      value: ""
    validations:
      required: true
  - type: textarea
    id: what-platform
    attributes:
      label: What operating system are you using?
      value: ""
    validations:
      required: true
  - type: textarea
    id: what-method
    attributes:
      label: Are you running my-yt directly with node.js or Docker?
      value: ""
    validations:
      required: true